# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Konglomerat e.V.
email: vorstand@listen.konglomerat.org
description: >
  Das Konglomerat ist ein Verein der Menschen rund um das Thema DIY (Do it
  yourself) zusammenbringt und ihnen die gemeinsame Nutzung von
  Räumlichkeiten, Werkzeug, Material und Know-How bei ihren Projekten
  ermöglicht.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://konglomerat-org.github.io" # the base hostname & protocol for your site
github_username:

# Build settings
markdown: kramdown
gems:
  - jemoji
